name: Deploy NextJS app

on:
  workflow_call:
    inputs:
      deployment_host:
        required: true
        type: string
      node_version:
        type: string
        default: 18.x
    secrets:
      ssh_private_key:
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Write SSH key
        run: echo $SSH_PRIVATE_KEY >> ./deployment_ssh_private_key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ssh_private_key }}

      - name: Copy project to deployment server
        run: scp -i ./deployment_ssh_private_key -r ./ "root@${DEPLOYMENT_HOST_IP}:/deployments/${REPO_NAME}"
        env:
          DEPLOYMENT_HOST_IP: ${{ inputs.deployment_host }}
          REPO_NAME: ${{ github.repository }}

